site_name: Superb Data Kraken - Documentation
repo_url: https://github.com/efs-opensource/superb-data-kraken-docs
strict: true
theme:
  name: material
  custom_dir: docs/overrides
  favicon: assets/favicon.svg
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo-white.svg
  palette:

  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.footer
  - content.tooltips
extra_css:
- stylesheets/extra.css
markdown_extensions:
- abbr
- admonition
- attr_list
- codehilite
- footnotes
- md_in_html
- pymdownx.inlinehilite
- pymdownx.superfences
- pymdownx.details
- toc:
    permalink: true
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.snippets:
    auto_append:
    - includes/glossary.md
- pymdownx.tasklist:
    custom_checkbox: true
extra:
  generator: false
nav:
- Home: README.md
- User Guide:
  - user-guide/quick-start.md
  - user-guide/walk-through.md
  - user-guide/howtos.md
  - user-guide/admin-guide.md
- Architecture:
  - architecture/index.md
  - architecture/roles-and-rights.md
- Operator Manual:
  - operator-manual/prerequesits.md
  - operator-manual/installation.md
- Developer Guide:
  - developer-guide/CONTRIBUTING.md
  - developer-guide/branching-guidelines.md
  - developer-guide/git-commands.md
  - developer-guide/git-commit-guidelines.md
  - developer-guide/pull-request-template.md
#- Glossary: glossary.md
