@startuml
actor User
User -> MetadataService: CRUD Organization-Context [http/https]
MetadataService --> MetadataService: Validate Request

group send requests
    MetadataService -> Keycloak: Request ServiceAccount-Token [http]
    Keycloak -> MetadataService: Response [http]
    MetadataService -> OpenSearch: CRUD Tenant [http]
    note right: use of ServiceAccount-Token
    OpenSearch -> MetadataService: Response [http]
    MetadataService -> OpenSearch: CRUD Roles [http]
    note right: use of ServiceAccount-Token
    OpenSearch -> MetadataService: Response [http]
    MetadataService -> OpenSearch: CRUD RolesMappings [http]
    note right: use of ServiceAccount-Token
    OpenSearch -> MetadataService: Response [http]
end
MetadataService -> User: Response [http/https]
@enduml