@startuml
actor User
User -> MetadataService: CRUD metadata [http/https]
MetadataService --> MetadataService: Validate Request

group send requests
    MetadataService -> Keycloak: Request ServiceAccount-Token [http]
    Keycloak -> MetadataService: Response [http]
    MetadataService -> OpenSearch: index to measurement-Index [http]
    note right: use of ServiceAccount-Token
    OpenSearch -> MetadataService: Response [http]
    group deprecated
        MetadataService -> Schemamanager: index model [http]
        note right: current workaround to enable users to list properties in their indices
        Schemamanager -> MetadataService: Response [http]
    end
    MetadataService -> EventHub: send "indexing-done" [Kafka]
    EventHub -> MetadataService: Response
end
MetadataService -> User: Response [http/https]
@enduml