@startuml
actor User
User -> Storagemanager: CRUD Storage [http/https]
Storagemanager --> Storagemanager: Validate Request

group send requests
    Storagemanager -> AzureStorage: CRUD Storage
    note right: use of a storage principal
    AzureStorage -> Storagemanager: Response
end
Storagemanager -> User: Response [http/https]
@enduml