@startuml

rectangle "Azure Blob Storage" {
    database "Storage Account (Organization1)" {
        node "Storage Container (loadingzone for Organization1)"
        node "Storage Container (Space1 in Organization1)"
        node "Storage Container (Space2 in Organization1)"
    }
    database "Storage Account (Organization2)" {
        node "Storage Container (loadingzone for Organization2)"
        node "Storage Container (Space1 in Organization2)"
        node "Storage Container (Space2 in Organization2)"
    }
}


@enduml