@startuml
actor Admin
Admin -> Organizationmanager: CRUD Permission [http/https]
Organizationmanager --> Organizationmanager: Validate Request
Organizationmanager --> Organizationmanager: persist Entity

group send requests
    Organizationmanager -> Keycloak: CRUD Permission [http]
    Keycloak -> Organizationmanager: Response [http]
end
Organizationmanager -> Admin: Response [http/https]
@enduml